### ISSUE TITLE
doesn't work with propshaft

### ISSUE THREAD

**Issue by alec-c4** [rmosolgo/graphiql-rails#108]
Hi!
This gem doesn't work with propshaft - it freezes with 'Loading' message. Are there any plans to add propshaft support?

**Comment by omidian** [comment]
I have the same issue on rails 7.0.6
![image](https://github.com/rmosolgo/graphiql-rails/assets/9625851/cfb8623f-0d59-4328-b43e-8c1d40aef941)

**Comment by rmosolgo** [comment]
Hi! I just released graphiql-rails 1.10.0 which works with Propshaft (via #116)
