### ISSUE TITLE
Persist headers always resets to "false"

### ISSUE THREAD

**Issue by macgill4444** [rmosolgo/graphiql-rails#121]
I'm running into an issue where every time I enable "Persist headers", it reverts to back to disabled after one or two reloads of the page. Any idea on how to fix this?

**Comment by rmosolgo** [comment]
Hi! It looks like this is a bug in GraphiQL upstream: https://github.com/graphql/graphiql/issues/3369

There's nothing I can do in Graphiql-rails to address it, although that issue discussion has a proposed work-around. I hope it works for you!

**Comment by macgill4444** [comment]
Okay cool. Thanks so much for your help!
