### ISSUE TITLE
fix typo in the repo description

### ISSUE THREAD

**Issue by kirillseva** [rmosolgo/graphiql-rails#20]
must be GraphiQL
![screen shot 2017-05-05 at 1 42 27 pm](https://cloud.githubusercontent.com/assets/4439480/25759583/c78fc08a-3198-11e7-8d82-4f88092a2cf3.png)

**Comment by rmosolgo** [comment]
Thank you! How embarrassing. I've just fixed it!

**Comment by kirillseva** [comment]
it's opensource, if you're not embarrassed you're not doing it right :)
Thank you for the library, looking forward to using it in my next project
