### ISSUE TITLE
Version 1.4.5 raises React errors

### ISSUE THREAD

**Issue by mrcasals** [rmosolgo/graphiql-rails#28]
Hi!

I'm using version 1.4.5 and I'm getting React errors:

![](https://i.imgur.com/FnnoU2M.png)

Sadly, I don't know enough Rect to fix them, and the diff for v1.4.5 doesn't seem to modify many things:

https://github.com/rmosolgo/graphiql-rails/compare/c2dc1d8f93ddcecd900512e279185bf6c00509e0...master

So I cannot pinpoint where the error is. Can you help with that?

Thanks!

**Comment by rmosolgo** [comment]
Hey, sorry this popped up. I hope a newer release addressed the problem. If anyone runs into this again, please open a new issue!
