### ISSUE TITLE
Version1.4.6 raise error "process is not defined"

### ISSUE THREAD

**Issue by naokikurosawa** [rmosolgo/graphiql-rails#33]
React 16 seems to assume NodeJS environment variables.

<img width="1226" alt="2017-10-29 23 58 45" src="https://user-images.githubusercontent.com/8499749/32145010-2c5eb438-bd05-11e7-9a86-0163eff2bfc1.png">

**Comment by vigneshacker** [comment]
For me also the same error is popping out.

**Comment by wmaciejak** [comment]
For me the same 🤔

**Comment by rmosolgo** [comment]
Sorry the for the trouble! It looks like we had the wrong React files bundled in. Fixed in #35 and released a fix on RubyGems as 1.4.7, could you give a try and let me know if it's better for you?

**Comment by vigneshacker** [comment]
@rmosolgo sure. I will try and let u know.

**Comment by naokikurosawa** [comment]
@rmosolgo It looks good to me!

**Comment by rmosolgo** [comment]
It sounds like a previous fix addressed this :+1:
