### ISSUE TITLE
Version 1.4.6 show's loading on graphiql_path

### ISSUE THREAD

**Issue by 0sc** [rmosolgo/graphiql-rails#34]
`Loading...` screen when visiting `graphiql_path` 

<img width="491" alt="screen shot 2017-10-31 at 4 24 26 pm" src="https://user-images.githubusercontent.com/11221027/32232934-79a10d36-be59-11e7-8b3b-dfc356cdf16c.png">

## To reproduce, run
* `rails new graphql-sample`
* `cd graphql-sample`
* `echo gem "'graphql'" >> Gemfile`
* `bundle install`
* ` rails g graphql:install`
* `bundle install `
* `rails s`

then visit `localhost:3000/graphiql`

**Comment by rmosolgo** [comment]
Thanks for the great bug report! I found the bug, see #35. I've pushed a new version (1.4.7) to RubyGems, could you give it a try?

**Comment by 0sc** [comment]
Cool @rmosolgo, `v1.4.7` fixes it. Thanks for the quick turn around.

Closing this now

**Comment by kalicki** [comment]
Hi
I have this same problem in the version `graphiql-rails 1.4.9`

![screen_bug](https://user-images.githubusercontent.com/3674885/36938998-d8372cb2-1f08-11e8-8718-ab2954f46908.png)

**Comment by kalicki** [comment]
I tried the `1.4.7` version, which by the comments could resolve, but not.

**Comment by jeperkins4** [comment]
I was having a similar issue between development and staging environments.  The fix for me was to change the settings in config/environments/staging.rb...

`config.assets.compress = false`
