### ISSUE TITLE
Why is rails a dependency?

### ISSUE THREAD

**Issue by TSMMark** [rmosolgo/graphiql-rails#37]
This looks just like a simple Rack app that you can mount in any Rack router. Does it work with sinatra / cuba / roda?

**Comment by rmosolgo** [comment]
At the time, a Rails engine was the best technique I knew. These days, I'd love to explore a rack-based alternative, see https://github.com/rmosolgo/graphql-ruby/issues/1051

As a Rails engine, this project uses Rails structure, see https://github.com/rmosolgo/graphiql-rails/tree/master/app

**Comment by ryanmt** [comment]
Furthermore, requiring `rails` itself is a bad practice, as it requires installation of often unnecessary dependencies (like actioncable, etc) for all cases.  For instance, in rails 5, the API mode doesn't install those features to new apps either, but depending on this gem would bring those in.

Addressing this can be fairly simple as just replacing `s.add_runtime_dependency "rails"` with `  s.add_runtime_dependency "railties"` in the gemspec gets you most of the way.  

I'll push up a PR to address that.

**Comment by rmosolgo** [comment]
That'd be great!

**Comment by rmosolgo** [comment]
(dang it, wrong button!)

**Comment by rmosolgo** [comment]
I don't think there's any further action on this PR, so I'll close it.
