### ISSUE TITLE
uninitialized constant GraphiQL (NameError) when set to load in other environments

### ISSUE THREAD

**Issue by bytewalls** [rmosolgo/graphiql-rails#41]
I have two environments configured in which I would like to use GraphiQL (my app behaives slightly differently in an enterprise mode than a development mode and have dev environments for both)

When loading the enterprise development environment I get the above error. GraphiQL should be capable of being mounted in any environment.

**Comment by rmosolgo** [comment]
Yes, it _should_ be capable to be loaded in any environment! Have you done anything to debug yet? 

For example, did you check the entry in your Gemfile? It's not scoped to `:development`, is it? Are there any differences in how gems are `require`d in the enterprise environment? (Maybe it needs a manual `require "graphiql/rails"`?)

**Comment by bytewalls** [comment]
Woops doh, didn't realize it was automatically added for only development group.

**Comment by rmosolgo** [comment]
Glad you got to the bottom of it!
