### ISSUE TITLE
Work with API only app

### ISSUE THREAD

**Issue by sarink** [rmosolgo/graphiql-rails#53]
I'm encountering this issue https://github.com/rmosolgo/graphiql-rails/issues/42 and I believe that the problem is due to using a rails 5 api only app.

Tried following these instructions https://github.com/rmosolgo/graphiql-rails/issues/13#issuecomment-256256255 but they appear to be outdated.

Is there any way to make this gem work with an API app?

**Comment by sarink** [comment]
Update: Figured this out myself. The only thing necessary (rails 5.2.0) is to add the following line to `application.rb`
```
    config.middleware.use Rack::MethodOverride
```

**Comment by rmosolgo** [comment]
Glad you found a solution, and thanks for sharing it! Feel free to open a PR to the readme if you're interested.

**Comment by Li357** [comment]
If you're experiencing the error:

    Expected to find a manifest file in `app/assets/config/manifest.js` (Sprockets::Railtie::ManifestNeededError)

With Rails 6/Sprockets 4, downgrade to Sprockets 3 by adding this to your `Gemfile`:

    gem 'sprockets', '~> 3'

And running `bundle update sprockets`

**Comment by aharasta** [comment]
People starting new projects with Rails 6 in API mode will encounter issue @Li357 has pointed out. Thanks for the solution!

**Comment by Aryk** [comment]
Thanks @Li357! `gem 'sprockets', '~> 3'` worked!

**Comment by JamesLivengood** [comment]
I did all of the above but still getting this error: 
```No route matches [GET] "/graphiql"```

**Comment by areph** [comment]
Thanks @Li357!

**Comment by manhhung741** [comment]
You don't need to downgrade sprocket, just add a manifest.js file and it'll work:
See: https://github.com/rmosolgo/graphiql-rails/issues/13#issuecomment-640366886

**Comment by RobertWSaunders** [comment]
FYI, if you don't want to run on a lower `sprockets` version you can just do:

1. Create the manifest file:

`touch app/assets/config/manifest.js`

2. Add links to the GraphiQL CSS and JS files so they get loaded:

```
//= link graphiql/rails/application.css
//= link graphiql/rails/application.js
```

**Comment by redferret** [comment]
> Update: Figured this out myself. The only thing necessary (rails 5.2.0) is to add the following lines to `application.rb`
> 
> ```
> require "sprockets/railtie"
> 
> config.middleware.use Rack::MethodOverride
> ```
> 
> Closing. But it might be nice to add it to the readme!

Can you explain why you picked this?
Reading in the docs I find this for `Rack::MethodOverride`
```
Allows the method to be overridden if params[:_method] is set. This is the middleware which supports the PUT and DELETE HTTP method types.
```
