### ISSUE TITLE
support for passing headers

### ISSUE THREAD

**Issue by chevinbrown** [rmosolgo/graphiql-rails#57]
There is currently no ability to pass headers--since bearer token/JWT is fairly common this makes using this library pretty difficult.

I'm going to fool around with merging this library into this one because it's a joy to use: 

https://github.com/OlegIlyenko/graphiql-workspace

Would you be open to something like that, or at a minimum adding header support?

**Comment by chevinbrown** [comment]
After playing with this for just a few minutes, the react project above has a lot of niceties that this project could benefit from.

How would you feel about wrapping that library?

**Comment by rmosolgo** [comment]
Hi, I think it's be a great idea to have a Ruby-ready wrapper of that project! I think it would be possible to make an event _better_ library, too, making a Rack app instead of a Rails engine, so that even non-Rails (and non-Sprockets) apps could use it. Let me know how it goes!

**Comment by rmosolgo** [comment]
It's probably out-of-scope. I mean, you're talking about accepting user input then sending that along with requests, right? So it would need a UI and glue code? My impression is that time would be better spent wrapping graphql-workspace, since it has so many _other_ good features!

**Comment by chevinbrown** [comment]
Correct--with this library, there's no way to pass a JWT/Bearer token as a header. 

It's really sad about OSS...so little time and so much that the community needs.
