### ISSUE TITLE
GraphIQL does not remember queries, as it does in the default library.

### ISSUE THREAD

**Issue by jwaldrip** [rmosolgo/graphiql-rails#6]
If you go to graphql.brandfolder.com and enter the following query, on reload it persists. This is a feature of the native graphIQL, would like to know why it isn't present in the rails version.

```
{
  slug(uri: "brandfolder") {
    id
  }
}
```

**Comment by rmosolgo** [comment]
Oops, it was overriding `query` instead of `defaultQuery`. Also, I maybe GraphiQL has an error regarding defaultQuery (https://github.com/graphql/graphiql/pull/130). I patched the vendored version by hand. 

Could you try version 1.2.0? (It also has GraphiQL 0.7.0)

**Comment by rmosolgo** [comment]
Hope this looks better for you on a recent version!
