### ISSUE TITLE
Explorer

### ISSUE THREAD

**Issue by bleonard** [rmosolgo/graphiql-rails#64]
This looks pretty helpful. Any interest in integrating?
https://github.com/OneGraph/graphiql-explorer

**Comment by leofrozenyogurt** [comment]
+1 for integrating

**Comment by rubendinho** [comment]
Has anyone been able to get this working?

**Comment by djoksimo** [comment]
+1 for integrating

**Comment by fabn** [comment]
Is there any news for this? It would be great to have it bundled.

**Comment by cdeliens** [comment]
Was someone able to make this work?
