### ISSUE TITLE
Current GraphiQL version not compatible with graphql-ruby 1.9.x

### ISSUE THREAD

**Issue by the-codetrane** [rmosolgo/graphiql-rails#67]
I have been trying to use this version of `graphiql-rails` with `graphql` version 1.9.3, which gave me the below response. When I ported back to 1.18.0, the proper response came through. I apologize that I can't make a PR myself to resolve this at the moment, since I'm a total n00b to GraphQL, but I wanted to make you aware for your next release. 

Big fan of the tool, so thank you for the work y'all have done!

Michael

## Mutation Type
```ruby
class Types::MutationType < GraphQL::Schema::Object
  field :updateUser, mutation: Mutations::UpdateUser
end
```
## Mutation 
```ruby
class Mutations::UpdateUser < Mutations::BaseMutation

  argument :id, ID, required: true
  argument :name, String, required: false
  argument :title, String, required: false
  argument :role, Int, required: false

  field :user, Types::UserType, null: true
  field :errors, [String], null: false

  def resolve( id:, name:, title:, role:)
    user = User.find(id)
    if user.update(name: name, title: title, role: role)
      {
        user: user,
        errors: []
      }
    else
      {
        user: nil,
        errors: []
      }
    end
  end
end
```
## GraphQL mutation
```javascript
mutation updateUser($id: ID!, $name: String, $title: String, $role: Int) {
  updateUser(id:$id, name: $name, title: $title, role:$role) {
    user {
      name
      id
    }
  }
}

// Query Values

{
  "id": 1,
  "name": "Mr. Smith",
  "title": "President",
  "role": 3
}
```
## Return value

```javascript
{
  "data": {
    "updateUser": {
      null
    }
  }
}
```

**Comment by the-codetrane** [comment]
It would appear that these breaking changes are what's causing the issue:

## 1.8.7 (9 Aug 2018)
### Breaking changes
- Some mutation authorization hooks added in 1.8.5 were changed, see #1736 and #1737. Roughly:
   - `before_prepare` was changed to `#ready?`
   - `validate_* hooks` were replaced with a single `#authorized?` method

### Bug fixes
- Argument default values include nested default values #1728
- Clean up duplicate method defs #1739

### New features
- Built-in support for Mongoid 5, 6, 7 #1754
- Mutation `#ready?` and `#authorized?` may halt flow and/or return data #1736, #1737
- Add `.scope_items(items, ctx)` hook for filtering lists
- Add `#default_graphql_name` for overriding default logic #1729
- Add `#add_argument` for building schemas #1732
- Cursors are decoded using `urlsafe_decode64` to future-proof for urlsafe cursors #1748

**Comment by ACPK** [comment]
@the-codetrane  - This gem doesn't unless we downgrade to an older version of graphql?

**Comment by the-codetrane** [comment]
@ACPK that would appear to be the case. These were the breaking changes I found that interfered with the gem. Now, this may have been resolved with v. 1.9.7. I was working with 1.9.3 at the time.

**Comment by the-codetrane** [comment]
Closed per new releases.
