### ISSUE TITLE
AbstractController::ActionNotFound (The action 'execute' could not be found for GraphqlController):

### ISSUE THREAD

**Issue by hugoh59** [rmosolgo/graphiql-rails#74]
Using Rails 6.x and --api app I get the above error.

This Stackoverflow thread describes the issue.
https://stackoverflow.com/questions/58403931/the-action-execute-could-not-be-found-for-graphqlcontroller-when-using-graph

**Comment by rmosolgo** [comment]
It looks like this was solved on StackOverflow. Please open a new issue if you have any more trouble with it!
