### ISSUE TITLE
GraphiQL::Rails::EditorsController#show raising on new Rails 6 app

### ISSUE THREAD

**Issue by kurko** [rmosolgo/graphiql-rails#80]
After `rails g graphql:install`, accessing the view raises this in `development`:

```
Started GET "/graphiql" for 172.19.0.1 at 2020-01-19 01:45:59 +0000
Processing by GraphiQL::Rails::EditorsController#show as HTML
  Parameters: {"graphql_path"=>"/graphql"}
  Rendering /usr/local/bundle/gems/graphiql-rails-1.7.0views/graphiql/rails/editors/show.html.erb
  Rendered /usr/local/bundle/gems/graphiql-rails-1.7.0views/graphiql/rails/editors/show.html.erb (Duration: 171.3ms | Allocations: 4865)
Completed 500 Internal Server Error in 211ms (ActiveRecord: 0.0ms | Allocations: 6087)
```

I'm having a hard time figuring out the stack trace. Will post back when I get to it.

Any ideas in the mean time?

**Comment by kurko** [comment]
Nvm. It was a problem with another gem (xray). Removing that fixed the issue. Then I faced https://github.com/rmosolgo/graphiql-rails/issues/75, but fixed it.

**Comment by jesster2k10** [comment]
@kurko  Hey, I got this same issue but I don't have any X-ray gem installed. Do you know what the specific cause of the issue was

**Comment by kurko** [comment]
@jesster2k10 it was just xray, really. I removed it and things worked. Have you checked your Gemfile.lock? This was a brand new project I was experimenting with.
