### ISSUE TITLE
Is this gem dead?

### ISSUE THREAD

**Issue by darylf** [rmosolgo/graphiql-rails#87]
I don't see any updates since **January 2019**. There are many open, unanswered issues.

I don't fault the owner for abandoning it, and I fully acknowledge that maintaining open source is difficult. I'd just like to know if there are any plans to update this, or should we consider looking for alternate solutions elsewhere.

**Comment by rmosolgo** [comment]
Hey, the fact that this went unanswered for 3+ years may be an answer in itself ... the truth is, the gem has kept working for me whenever I needed it so I didn't prioritize things here 🙈 . 

I'm going to release 1.10.0 soon with updated assets and Propshaft support.
