### ISSUE TITLE
sass not needed anymore?

### ISSUE THREAD

**Issue by jjb** [rmosolgo/graphiql-rails#97]
Hi, thanks for a great project!

graphiql seems to work fine in rails 6.1 without the sass gem - is this new in 6.1 vs 6, or is the readme wrong, or am i mistaken because something is maybe cached?

these two seem to be generated just fine

/assets/graphiql/rails/application-...js
/assets/graphiql/rails/application-...css

**Comment by rmosolgo** [comment]
I think it might be a change in Rails. I just generated a new Rails 7 app and the relevant lines were commented out: 

```ruby
  # Compress CSS using a preprocessor.
  # config.assets.css_compressor = :sass
```

This gem doesn't have any sass, so I think we can get rid of that note in the readme.
